/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        black: 'rgb(var(--gus-color-black) / <alpha-value>)',
        white: 'rgb(var(--gus-color-white) / <alpha-value>)',
        neutral: {
          50: 'rgb(var(--gus-color-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--gus-color-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--gus-color-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--gus-color-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--gus-color-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--gus-color-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--gus-color-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--gus-color-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--gus-color-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--gus-color-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--gus-color-neutral-950) / <alpha-value>)',
        },
      },
      spacing: {
        px: 'var(--gus-space-px)',
        0: 'var(--gus-space-0)',
        0.5: 'var(--gus-space-0_5)',
        1: 'var(--gus-space-1)',
        1.5: 'var(--gus-space-1_5)',
        2: 'var(--gus-space-2)',
        2.5: 'var(--gus-space-2_5)',
        3: 'var(--gus-space-3)',
        3.5: 'var(--gus-space-3_5)',
        4: 'var(--gus-space-4)',
        5: 'var(--gus-space-5)',
        6: 'var(--gus-space-6)',
        7: 'var(--gus-space-7)',
        8: 'var(--gus-space-8)',
        9: 'var(--gus-space-9)',
        10: 'var(--gus-space-10)',
        11: 'var(--gus-space-11)',
        12: 'var(--gus-space-12)',
        14: 'var(--gus-space-14)',
        16: 'var(--gus-space-16)',
        20: 'var(--gus-space-20)',
        24: 'var(--gus-space-24)',
        28: 'var(--gus-space-28)',
        32: 'var(--gus-space-32)',
        36: 'var(--gus-space-36)',
        40: 'var(--gus-space-40)',
        44: 'var(--gus-space-44)',
        48: 'var(--gus-space-48)',
        52: 'var(--gus-space-52)',
        56: 'var(--gus-space-56)',
        60: 'var(--gus-space-60)',
        64: 'var(--gus-space-64)',
        72: 'var(--gus-space-72)',
        80: 'var(--gus-space-80)',
        96: 'var(--gus-space-96)',
      },
      fontFamily: {
        sans: ['var(--gus-font-family-sans)'],
        mono: ['var(--gus-font-family-mono)'],
      },
      fontSize: {
        xs: ['var(--gus-font-size-xs)', { lineHeight: 'var(--gus-line-height-xs)' }],
        sm: ['var(--gus-font-size-sm)', { lineHeight: 'var(--gus-line-height-sm)' }],
        base: ['var(--gus-font-size-base)', { lineHeight: 'var(--gus-line-height-base)' }],
        lg: ['var(--gus-font-size-lg)', { lineHeight: 'var(--gus-line-height-lg)' }],
        xl: ['var(--gus-font-size-xl)', { lineHeight: 'var(--gus-line-height-xl)' }],
        '2xl': ['var(--gus-font-size-2xl)', { lineHeight: 'var(--gus-line-height-2xl)' }],
        '3xl': ['var(--gus-font-size-3xl)', { lineHeight: 'var(--gus-line-height-3xl)' }],
        '4xl': ['var(--gus-font-size-4xl)', { lineHeight: 'var(--gus-line-height-4xl)' }],
        '5xl': ['var(--gus-font-size-5xl)', { lineHeight: 'var(--gus-line-height-5xl)' }],
      },
      fontWeight: {
        normal: 'var(--gus-font-weight-normal)',
        medium: 'var(--gus-font-weight-medium)',
        semibold: 'var(--gus-font-weight-semibold)',
        bold: 'var(--gus-font-weight-bold)',
        extrabold: 'var(--gus-font-weight-extrabold)',
      },
    },
  },
  plugins: [],
};
